# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-05 01:32
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('public', models.BooleanField(default=True)),
                ('next_time', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoID', models.CharField(default='0', max_length=200)),
                ('title', models.CharField(default='default title set in Model', max_length=200)),
                ('duration', models.DurationField(default=datetime.timedelta(0, 30))),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('played', models.BooleanField(default=False)),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploader_user', to=settings.AUTH_USER_MODEL)),
                ('voters', models.ManyToManyField(blank=True, related_name='vote_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='current_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currently_playing', to='PartyPlay.Video'),
        ),
        migrations.AddField(
            model_name='room',
            name='favorite_users',
            field=models.ManyToManyField(blank=True, related_name='favorite_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
