# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartyPlay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='room',
            name='url',
            field=models.CharField(default='<django.db.models.fields.CharField>', max_length=200, primary_key=True, serialize=False),
        ),
    ]
