# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 01:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PartyPlay', '0002_auto_20170913_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='voters',
            field=models.ManyToManyField(related_name='vote_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploader_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
