# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 02:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PartyPlay', '0003_auto_20170915_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='rank',
        ),
    ]
