# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 19:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartyPlay', '0004_remove_video_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_length',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
