# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 19:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartyPlay', '0005_video_video_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_length',
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0, 10)),
        ),
    ]
