# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-21 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PartyPlay', '0008_auto_20170921_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='currently_video',
            new_name='current_video',
        ),
    ]
