# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 00:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PartyPlay', '0010_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='User',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ViewingRoom',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
