# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PartyPlay', '0011_auto_20170921_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='current_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currently_playing', to='PartyPlay.Video'),
        ),
        migrations.AlterField(
            model_name='room',
            name='next_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
