# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 00:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartyPlay', '0013_auto_20170924_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='vote_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
