# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 22:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartyPlay', '0014_auto_20170924_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0, 30)),
        ),
    ]
