# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-26 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartyPlay', '0015_auto_20170925_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='videoID',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
