# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-26 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PartyPlay', '0016_video_videoid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_name',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
    ]
