# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-04 04:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PartyPlay', '0019_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_rooms',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
