# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-04 04:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PartyPlay', '0020_auto_20171003_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='favorite_users',
            field=models.ManyToManyField(blank=True, related_name='favorite_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
