# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-05 01:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PartyPlay', '0021_room_favorite_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PartyPlay.Room'),
        ),
        migrations.AlterField(
            model_name='video',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploader_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
