# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-05 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartyPlay', '0022_auto_20171004_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='url',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
    ]
